# Generated by Django 3.2.25 on 2025-10-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20250929_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Коммерческое предложение', max_length=200, verbose_name='Название')),
                ('image', models.ImageField(upload_to='commercial_proposals/', verbose_name='Изображение')),
                ('alt_text', models.CharField(blank=True, default='Коммерческое предложение', max_length=200, verbose_name='Альтернативный текст')),
                ('description', models.TextField(default='Подробная информация о стоимости услуг', max_length=500, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активное')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Коммерческое предложение',
                'verbose_name_plural': 'Коммерческие предложения',
                'ordering': ['-created_at'],
            },
        ),
    ]
