# Generated by Django 3.2.25 on 2026-04-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_contactinfo_email_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратные звонки',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('website.serviceapplication',),
        ),
    ]
