# Generated by Django 3.2.25 on 2026-04-19 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_serviceapplication_tenderinvitation_full_name_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceapplication',
            name='agreed_to_processing',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку ПДн'),
        ),
    ]
